### ISSUE TITLE
Be ready for serialport-rs v2.0

### ISSUE THREAD

**Issue by berkowski** [berkowski/mio-serial#2]
Development work in the `serialport-2` branch.

@ndusart provided the majority of the API adaption with #1. 

TODO:
- [ ] Fix upstream issues until OSX/BSD targets compile (when nix v0.10 releases?)
- [x] Pull windows implementation @ndusart (#4)
- [x] Tag `serialport-rs` to a released version instead of git in `Cargo.toml`
- [x] Tag `nix` to a released version instead of git in `Cargo.toml`

**Comment by Susurrus** [comment]
Well it was just released today, so I hope you're ready!

**Comment by berkowski** [comment]
Not quite ready, but then I'll never be ahead of things.  I'll start looking into things this week.

**Comment by ndusart** [comment]
Actually, if you want the build for OSX to pass, you'll have to wait that iokit-sys is fixed and published anyway ;-)

**Comment by berkowski** [comment]
First go looks promising: https://travis-ci.org/berkowski/mio-serial/builds/320715034

Unfortunately BSD targets don't look like they're going to work with nix 0.9

**Comment by Susurrus** [comment]
I'm hoping to have nix 0.10 released within the next couple of weeks. It's blocking on a single PR that's being reviewed right now so I think that's a realistic timeframe.

**Comment by berkowski** [comment]
Added #4 to the TODO list for serialport-2

**Comment by Susurrus** [comment]
Both nix 0.10 and serialport-rs 2.1 have been released, which should make this all ready to go on your end.

**Comment by ndusart** [comment]
@berkowski yes, all points are resolved now
I updated #4 to use release 0.10 of nix and 2.1 of serialport

Thanks @Susurrus for all your work

**Comment by berkowski** [comment]
Things are good enough for me to merge the serialport-2 branch into master and start finalizing a new version release for mio and tokio.  Thank you @ndusart  and @Susurrus  for all the work (and perhaps more, all the patience!)
