### ISSUE TITLE
mio 0.7 support

### ISSUE THREAD

**Issue by jmaygarden** [berkowski/mio-serial#23]
I was about to fork and add support for mio 0.7. It's mostly a matter of switching from Evented to event::Source. However, @raffber has already done so in raffber/mio-serial. It would be great if his change could be pulled in and pushed to crates.io.

**Comment by berkowski** [comment]
A quick glance through @raffber's changes for mio-serial and tokio-serial looks OK.  I haven't had any use of tokio-serial for a good while now but I can pull his changes in and push new versions to crates.io

**Comment by berkowski** [comment]
Actually, looking closer none of the AsyncRead or AsyncWrite methods are implemented..

**Comment by raffber** [comment]
Yes, I have not done any significant work on this, since I quickly realized that I was stuck with tokio 0.2 / mio 0.6 due to some other dependencies. You can disregard my fork for the time being.

I might pick it back up in a few weeks but unfortunately I don't have time to work on this atm.

**Comment by berkowski** [comment]
Finally have some time to start moving on this.  On unix things look straight forward.  I'm waiting for guidance from tokio-rs/mio#1460

**Comment by berkowski** [comment]
Preliminary support for mio 0.7 has been added to the [v4.0](https://github.com/berkowski/mio-serial/tree/v4.0) branch

**Comment by ColinFinck** [comment]
I've tested the read_serialport example of the "v4.0_serialstream" branch under Windows and Linux and it works fine for me.
What is blocking the release of mio-serial v4.0?

**Comment by ColinFinck** [comment]
Bump

tokio 1.7.0 has just been released with support for Windows Named Pipes. This finally enables your [v4.4.0_serialstream branch of tokio-serial](https://github.com/berkowski/tokio-serial/tree/v4.4.0_serialstream) to be finished for Windows, and thereby release an updated tokio-serial for tokio 1.x.

But any work on tokio-serial requires this issue to be fixed first.
What is blocking it considering that the "v4.0_serialstream" branch seems to work fine?

**Comment by ColinFinck** [comment]
I'll be using the https://github.com/berkowski/mio-serial/tree/v4.0_serialstream branch for `mio-serial`, and my newly added https://github.com/enlyze/tokio-serial/tree/v4.4.0_serialstream_multiplatform branch for `tokio-serial` now.
This works well for me under Windows and Linux.

Requires pinning branches/revisions in `Cargo.toml` as long as they are not merged to master and released on crates.io.
But other than that, I'm finally able to use serial ports with mio 0.7.x and tokio 1.x.

**Comment by berkowski** [comment]
Started #25 as a roadmap to winding this up ahead of maintenance/transfer of ownership.

**Comment by berkowski** [comment]
version 4.0.0-beta1 is on crates.io with mio 0.7 support.
