### ISSUE TITLE
Missing 4.0.0-beta1 tag

### ISSUE THREAD

**Issue by lizapolyudova** [berkowski/mio-serial#26]
Hello

I am running into a build issue described in detail here(https://github.com/stepfunc/dnp3/issues/131) root cause of which seems to be that this repo is missing a tag called 4.0.0-beta1.

Seeing that there's now a tag called 4.0.0-beta2 tag I'm assuming beta1 used to exist but doesn't anymore?

I was wondering if you could restore the tag, since this was a breaking change

Thank you

**Comment by berkowski** [comment]
Tag should be restored, not sure how it got removed.  Certainly wasn't intentional.

**Comment by lizapolyudova** [comment]
very quick turnaround, thank you!

**Comment by berkowski** [comment]
I'm actively hacking on the repos at the moment :)  Trying to be careful because I know many people have been pointing a the repos directly due to my lack of published releases, but this probably won't be the last time something like this happens

**Comment by lizapolyudova** [comment]
Huh I'm thinking maybe something else was the root cause of the build issue. 
(the tag might have just been a red herring, I am not seeing the same issue anymore :( )

Getting the following build error now:

```
...

Caused by:
  failed to load source for dependency `mio-serial`

Caused by:
  Unable to update https://github.com/berkowski/mio-serial?branch=v4.0

Caused by:
  failed to find branch `v4.0`

Caused by:
  cannot locate remote-tracking branch 'origin/v4.0'; class=Reference (4); code=NotFound (-3)
```

looks like the branch is now missing?
here's the package pointing to the branch

https://github.com/stepfunc/tokio-serial/blob/f527f73e412c643fe3e691b27b4280e7b831d6d9/Cargo.toml#L27

possibly it makes more sense for it to point to a tag instead.
What's confusing to me about this error message, too is that the commit it's referring to

**Comment by berkowski** [comment]
No, it's certainly related to my work on `mio-serial` and `tokio-serial` this last week, and my long absence of any work before that.  All long-outstanding feature branches worth continuing have been merged to master at this point, and feature branches themselves deleted.

@stepfunc is using a forked version of `tokio-serial` before those changes were merged and beta versions pushed to crates.io.  I would encourage whatever project is using that forked version to try the posted betas on crates.io

**Comment by lizapolyudova** [comment]
Sigh ok. 

Do you know if it would be possible to restore state to make the project build (I know the project *definitely* built this past Thursday on the 15th)? (i.e. have the [presumably] previously existing branch `v4.0` exist and point to the same commit...
I don't think I have the commit hash, my cargo git cache from a previously working version is wiped :( )

I understand that it's probably against best practices to not to either:
* use a pinned version (something like a tag)
* or use master to make sure that library is using most recent version

but I have a deadline this upcoming Tuesday and not being able to build the project adds quite a twist. While I might be able to get away without re-building, it is extremely inconvenient and if any bugs are spotted, would be very unfortunate.

If it's not possible [to restore to the version at which the repo was on July 15th], I would understand and chat with the folks at stepfunc to use the newest version of the library (I will do that anyhow, since it seems like a good thing to do).
It's just, given the timeline I would really want to prioritize just getting to a state where I can build a binary...

Appreciate your help with this one!

**Comment by berkowski** [comment]
Luckily I still have the v4.0 branch locally.  I just pushed it back to github and can build dnp3 on my laptop.

**Comment by lizapolyudova** [comment]
you are amazing, thanks for all your help. 
I feel like I know so much more about the cargo build system after this whole story!

**Comment by berkowski** [comment]
In the meantime it seems like the changes to get `dnp3` compiling against `tokio-serial 5.4.0-beta1` are minimal.  I've submitted stepfunc/dnp3#133
