### ISSUE TITLE
mio-serial-4.0.0-beta3 fails to compile due to StdIoErrorKind::Unsupported

### ISSUE THREAD

**Issue by astraw** [berkowski/mio-serial#27]
Our CI server turned up the following new compilation error since the release of 4.0.0-beta3:

```
error[E0599]: no variant or associated item named `Unsupported` found for enum `std::io::ErrorKind` in the current scope
   --> /builds/straw/strand-braid/.cargo-proj/registry/src/github.com-1ecc6299db9ec823/mio-serial-4.0.0-beta3/src/lib.rs:516:50
    |
516 |             crate::ErrorKind::Io(StdIoErrorKind::Unsupported),
    |                                                  ^^^^^^^^^^^ variant or associated item not found in `std::io::ErrorKind`
```

Steps to reproduce:

```
git clone https://github.com/strawlab/strand-braid
cd strand-braid/camtrig
cargo check
```

This was using rustc 1.52.1 .

I'm really looking forward to mio-serial 4.0, thanks for your work on that!

**Comment by astraw** [comment]
git bisect tells me the guilty commit is 6f05a16766324c2e4313eeedbe26bbc1ccc2420f. And indeed here is the line in question: https://github.com/berkowski/mio-serial/commit/6f05a16766324c2e4313eeedbe26bbc1ccc2420f#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R515 . But I'm confused because the Unsupported variant of std::io::ErrorKind has existed since rust 1.6 according to [the docs](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.Unsupported).

**Comment by berkowski** [comment]
I didn't even think about that enum influencing the MSRV...

The docs are a little misleading.  If you look at the source (https://doc.rust-lang.org/stable/src/std/io/error.rs.html#95-189) it seems like `ErrorKind::Unsupported`, **was** introduced in `1.53.0`, not `1.6`.

Seems like if I revert back to `ErrorKind::Other` the MSRV drops to `1.40.0` using `crago msrv`, so while I really like the idea of using `ErrorKind::Unsupported` I think making the MSRV the current table version is a bit too much.

I'll push an update later today.

**Comment by berkowski** [comment]
`4.0.0-beta4` pushed to crates.io.  I've added CI checks against rustc-1.41.0 that pass

**Comment by astraw** [comment]
Ahh, I completely misread the docs. (I would argue the formatting is hard to read correctly.)

Yes, this was simply me not using the latest stable rust - if I had noticed that, I would not have filed a bug.

Thanks anyway for rolling back the MSRV and I'll have to remember `cargo msrv` for my own purposes.
